/* Integration tests only against the isolated loopback Supabase stack.
   Install pinned dependencies from client-package-lock.json in a temporary directory.
   ARVENA_TEST_MODULES points to its node_modules. No remote target is accepted. */
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {execFileSync}=require('node:child_process');
const crypto=require('node:crypto');
const {createClient}=require(process.env.ARVENA_TEST_MODULES+'/@supabase/supabase-js');
const cfg=JSON.parse(fs.readFileSync('/private/tmp/arvena-local-config.json','utf8'));
assert.equal(new URL(cfg.url).hostname,'127.0.0.1');
const make=()=>createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:false,autoRefreshToken:false}});
const anon=make(), clients={}, credentials={};let checks=0;
const ok=(truth,label)=>{assert.ok(truth,label);checks++;};
const sql=q=>execFileSync('docker',['exec','-i','supabase_db_arvena-platform-test','psql','-U','postgres','-v','ON_ERROR_STOP=1','-Atc',q],{encoding:'utf8'}).trim();
const t=(c,n)=>c.from('arvena_'+n);
const get=async p=>{const r=await p;if(r.error)throw new Error(r.error.message);return r.data;};
const denied=async(p,label)=>{const r=await p;ok(r.error||Array.isArray(r.data)&&r.data.length===0,label);};
const cmd=(c,command,payload)=>c.rpc('arvena_editor_command',{command,payload});
(async()=>{
 sql("notify pgrst, 'reload schema'");
 for(const name of ['a','b','providerA','providerB','contributor','specialist','editor']){
  const c=make(),email=`arvena-${name.toLowerCase()}-${crypto.randomUUID()}@example.test`,password=crypto.randomBytes(20).toString('base64url');
  const d=await get(c.auth.signUp({email,password}));ok(d.session,`local signup ${name}`);clients[name]=c;credentials[name]={email,password,id:d.user.id};
 }
 const {a,b,providerA,providerB,contributor,specialist,editor}=clients;
 const id=n=>credentials[n].id;
 sql(`insert into public.arvena_editors(user_id) values('${id('editor')}')`);
 const providers=await get(t(editor,'providers').insert(['A','B'].map(n=>({slug:'test-provider-'+n.toLowerCase(),name:'LOCAL TEST ONLY Provider '+n,summary:'Synthetic isolated security fixture',status:'published',relationship:'Synthetic test only'}))).select());
 const provider=n=>providers.find(p=>p.slug==='test-provider-'+n.toLowerCase());
 await get(t(editor,'provider_members').insert([{user_id:id('providerA'),provider_id:provider('A').id},{user_id:id('providerB'),provider_id:provider('B').id}]));
 async function packageOffer(name,domain='water'){
  const copy={slug:'test-offer-'+name.toLowerCase(),title:'LOCAL TEST ONLY Offer '+name,provider_id:provider(name).id,offer_type:'product',domain_slug:domain,need:'Synthetic test need',selection_rationale:'Synthetic review rationale',editorial_conclusion:'Synthetic only; not an Arvena recommendation',unknowns:'Unknown in fixture',limitations:'Test only',safety:'Not a real product',price:'Unknown',commercial_disclosure:'No real relationship',last_review_date:new Date().toISOString().slice(0,10),access_url:'https://example.com',claims:[]};
  const p=await get(cmd(editor,'save_package',{title:'LOCAL TEST ONLY package '+name,dossier:'PRIVATE DOSSIER SENTINEL',public_copy:copy}));
  await denied(cmd(editor,'publish_package',{id:p.id,revision:1}),'draft cannot publish');
  await get(cmd(editor,'review_package',{id:p.id,revision:1,status:'under_review'}));
  await denied(cmd(editor,'review_package',{id:p.id,revision:1,status:'approved',note:''}),'approval needs rationale');
  await get(cmd(editor,'review_package',{id:p.id,revision:1,status:'approved',note:'Human test approval for isolated fixture only'}));
  const offer=await get(cmd(editor,'publish_package',{id:p.id,revision:1}));return {...copy,id:offer.id,package_id:p.id};
 }
 const oa=await packageOffer('A'),ob=await packageOffer('B','air-and-indoor-environment');
 const publicOffers=await get(t(anon,'offers').select('*'));ok(publicOffers.length===2,'anonymous catalogue');ok(!JSON.stringify(publicOffers).includes('PRIVATE DOSSIER'),'dossiers absent from publication');
 await denied(t(anon,'research_packages').select('*'),'anonymous package denial');await denied(t(a,'research_packages').select('*'),'user package denial');
 await denied(cmd(a,'save_package',{title:'forged'}),'ordinary editor RPC denial');await denied(t(a,'editors').insert({user_id:id('a')}),'editor self elevation denied');
 await denied(t(a,'provider_members').insert({user_id:id('a'),provider_id:provider('A').id}),'provider self claim denied');
 await denied(t(a,'providers').update({name:'forged'}).eq('id',provider('A').id).select(),'public editing denied');
 await denied(t(a,'offers').update({title:'forged'}).eq('id',oa.id),'offer direct editing denied');
 await get(t(a,'saved_offers').upsert({offer_id:oa.id},{onConflict:'user_id,offer_id',ignoreDuplicates:true}));
 await get(t(a,'saved_offers').upsert({offer_id:oa.id},{onConflict:'user_id,offer_id',ignoreDuplicates:true}));
 ok((await get(t(a,'saved_offers').select('*'))).length===1,'duplicate saves safe');
 ok((await get(t(b,'saved_offers').select('*'))).length===0,'B cannot read A saves');
 await denied(t(b,'saved_offers').insert({user_id:id('a'),offer_id:ob.id}),'forged save owner denied');
 await denied(t(anon,'saved_offers').insert({user_id:id('a'),offer_id:ob.id}),'anon saves denied');
 await get(a.rpc('arvena_save_preferences',{p_region:'Europe',p_domains:['water']}));
 await denied(t(b,'profiles').update({region:'forged'}).eq('user_id',id('a')).select(),'B cannot edit A preferences');
 await denied(t(b,'profiles').insert({user_id:id('a'),region:'forged'}),'B cannot insert A preferences');
 ok((await get(t(a,'profiles').select('*')))[0].region==='Europe','preferences persisted');
 await denied(a.rpc('arvena_save_preferences',{p_region:'changed',p_domains:['not-real']}),'invalid domain denied');
 ok((await get(t(a,'profiles').select('*')))[0].region==='Europe','preferences transaction rollback');
 ok((await get(t(a,'interests').select('*'))).length===1,'interests transaction rollback');
 await denied(t(a,'contributions').insert({offer_id:oa.id,kind:'question',body:'Ordinary user question'}),'login not posting permission');
 await get(t(editor,'contribution_permissions').insert([{user_id:id('contributor'),offer_id:oa.id,capability:'contributor'},{user_id:id('specialist'),domain_slug:'water',capability:'specialist'}]));
 const contribution=(await get(t(contributor,'contributions').insert({offer_id:oa.id,kind:'question',body:'Synthetic permitted question'}).select()))[0];
 await denied(t(contributor,'contributions').insert({offer_id:ob.id,kind:'question',body:'Outside the allowed scope'}),'contributor scope denied');
 await denied(t(contributor,'contributions').insert({offer_id:oa.id,kind:'specialist_explanation',body:'Impersonating a specialist'}),'specialist impersonation denied');
 await denied(t(contributor,'contributions').insert({offer_id:oa.id,kind:'question',body:'Bypass moderation attempt',status:'published'}),'self publication denied');
 await get(t(specialist,'contributions').insert({offer_id:oa.id,kind:'specialist_explanation',body:'Synthetic reviewed specialist contribution'}));
 await get(t(providerA,'contributions').insert({offer_id:oa.id,kind:'provider_statement',body:'Synthetic provider statement'}));
 await denied(t(providerA,'contributions').insert({offer_id:ob.id,kind:'provider_statement',body:'Wrong provider statement'}),'provider contribution scope denied');
 await denied(t(providerA,'contributions').select('*').eq('id',contribution.id),'provider cannot read private questions');
 ok((await get(t(anon,'public_contributions').select('*'))).length===0,'pending not public');
 await denied(cmd(editor,'moderate',{id:contribution.id,status:'published'}),'review step required');
 await get(cmd(editor,'moderate',{id:contribution.id,status:'under_review'}));
 await get(cmd(editor,'moderate',{id:contribution.id,status:'published',body:'Reviewed public question text'}));
 const discussion=await get(t(anon,'public_contributions').select('*'));ok(discussion.length===1,'moderation publication');ok(!('user_id'in discussion[0]),'no public author account identifier');
 await get(cmd(editor,'moderate',{id:contribution.id,status:'hidden'}));ok((await get(t(anon,'public_contributions').select('*'))).length===0,'hidden not public');
 await get(t(editor,'contribution_permissions').delete().eq('user_id',id('contributor')));
 await denied(t(contributor,'contributions').insert({offer_id:oa.id,kind:'question',body:'Revoked permission test'}),'revocation immediate');
 const correction=(await get(t(providerA,'corrections').insert({offer_id:oa.id,body:'Synthetic factual correction'}).select()))[0];
 await denied(t(providerB,'corrections').select('*').eq('id',correction.id),'provider B correction isolation');
 await denied(t(providerA,'corrections').insert({offer_id:ob.id,body:'Other provider correction'}),'correction scope');
 await denied(t(a,'corrections').insert({offer_id:oa.id,body:'Ordinary user correction'}),'correction role');
 await get(cmd(editor,'review_correction',{id:correction.id,status:'resolved',note:'Synthetic editorial resolution'}));
 ok((await get(t(providerA,'corrections').select('*')))[0].status==='resolved','correction reviewed');
 const session=crypto.randomUUID();
 for(let i=0;i<2;i++)await get(anon.rpc('arvena_record_event',{p_offer:oa.id,p_kind:'view',p_session:session}));
 await get(anon.rpc('arvena_record_event',{p_offer:oa.id,p_kind:'outbound',p_session:session}));
 await get(providerA.rpc('arvena_record_event',{p_offer:oa.id,p_kind:'view',p_session:crypto.randomUUID()}));
 const metrics=await get(t(providerA,'listing_metrics').select('*'));ok(metrics.length===1&&metrics[0].views===1&&metrics[0].outbound_clicks===1,'measured deduped metrics and representative exclusion');
 ok((await get(t(providerB,'listing_metrics').select('*'))).length===0,'provider B analytics isolation');
 ok((await get(t(a,'listing_metrics').select('*'))).length===0,'ordinary analytics denial');
 await denied(t(anon,'listing_metrics').select('*'),'anonymous analytics denial');
 await denied(t(providerA,'listing_metrics').update({views:999}).eq('offer_id',oa.id),'analytics forgery denied');
 await denied(anon.schema('arvena_private').from('event_windows').select('*'),'raw events inaccessible');
 await get(cmd(editor,'save_package',{id:oa.package_id,revision:1,title:'Updated test package',dossier:'PRIVATE NEW DOSSIER',public_copy:{...oa,title:'Revised local fixture'}}));
 await denied(cmd(editor,'publish_package',{id:oa.package_id,revision:2}),'edited approval invalidated');
 await denied(cmd(editor,'save_package',{id:oa.package_id,revision:1,title:'stale',public_copy:{}}),'stale save rejected');
 ok((await get(t(anon,'offers').select('title').eq('id',oa.id)))[0].title===oa.title,'draft edits do not alter published copy');
 await get(cmd(editor,'hide_offer',{id:ob.id}));
 ok((await get(t(anon,'offers').select('id').eq('id',ob.id))).length===0,'hidden offer not public');
 await denied(t(a,'saved_offers').insert({offer_id:ob.id}),'hidden offer cannot be saved');
 await get(t(a,'saved_offers').delete().eq('offer_id',oa.id));ok((await get(t(a,'saved_offers').select('*'))).length===0,'save removal');
 await get(t(editor,'provider_members').delete().eq('user_id',id('providerA')));
 await denied(t(providerA,'corrections').insert({offer_id:oa.id,body:'Revoked provider correction'}),'provider revocation immediate');
 ok((await get(t(providerA,'listing_metrics').select('*'))).length===0,'revoked analytics hidden');
 // Restore authorized local fixtures for browser testing; never written to the public repository.
 await get(t(editor,'provider_members').insert({user_id:id('providerA'),provider_id:provider('A').id}));
 await get(t(editor,'contribution_permissions').insert({user_id:id('contributor'),offer_id:oa.id,capability:'contributor'}));
 fs.writeFileSync('/private/tmp/arvena-browser-fixtures.json',JSON.stringify({credentials,offer:oa,provider:provider('A')}),{mode:0o600});
 console.log(`PASS: ${checks} auth, publication, ownership, revocation, moderation and analytics assertions on isolated local Supabase.`);
})().catch(e=>{console.error('FAIL:',e.message);process.exitCode=1;});
